// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMi06bUtmbYgcrAFEbCq43gZNVEw-T3w',
    appId: '1:659622886805:android:0bf55f2f446052297aca9c',
    messagingSenderId: '659622886805',
    projectId: 'my-first-app-466bd',
    storageBucket: 'my-first-app-466bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUMX6R20I_oLLxbp4b9LGnA6lDDA5dl3A',
    appId: '1:659622886805:ios:1828857f9d6b4ee37aca9c',
    messagingSenderId: '659622886805',
    projectId: 'my-first-app-466bd',
    storageBucket: 'my-first-app-466bd.appspot.com',
    iosClientId: '659622886805-jqngp7fqketls7aijq7qf7p773d4cq1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstCoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUMX6R20I_oLLxbp4b9LGnA6lDDA5dl3A',
    appId: '1:659622886805:ios:1828857f9d6b4ee37aca9c',
    messagingSenderId: '659622886805',
    projectId: 'my-first-app-466bd',
    storageBucket: 'my-first-app-466bd.appspot.com',
    iosClientId: '659622886805-jqngp7fqketls7aijq7qf7p773d4cq1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstCoApp',
  );
}
