on:
  push:
    tags:
      - '*'
    branches:
      - main

name: Build and Release Apps

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure signature
        run: |
          echo "${{secrets.KEY_PROPERTIES}}" > android/key.properties
          echo "${{secrets.RELEASE_KEYSTORE}}" > upload-keystore.encoded
          base64 -d -i upload-keystore.encoded > ./android/app/upload-keystore.jks
      - uses: actions/setup-java@v1
        with:
          java-version: '19.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7'
          channel: stable
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build Android App
        run: flutter build apk --split-per-abi
      - name: Retrieve Release Version
        id: versionstep
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "::set-output name=VERSION::$VERSION"
      - name: Upload the APK onto Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/*.apk'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.versionstep.outputs.VERSION }}